-- Questions héritées d'OpenTriviaDB en unités impériales (pieds, livres, miles, mph) :
-- converties en métrique dans les deux langues, en gardant l'ordre des réponses (correctIndex inchangé).
-- Restent en impérial les questions dont l'unité est le sujet (°F, furlongs, inHg, unités SI)
-- et les 88 mph de Retour vers le futur.

UPDATE "Question" SET "answersEn" = '["828 m", "922 m", "776 m", "712 m"]'::jsonb, "answersFr" = '["828 m", "922 m", "776 m", "712 m"]'::jsonb WHERE "sourceId" = 'otd-SG93IHRhbGwgaXMgdGhlIEJ1cmogS2hhbGlmYT8=';
UPDATE "Question" SET "answersEn" = '["152 m", "131 m", "139 m", "121 m"]'::jsonb, "answersFr" = '["152 m", "131 m", "139 m", "121 m"]'::jsonb WHERE "sourceId" = 'otd-V2hhdCB3YXMgdGhlIGhlaWdodCBvZiBLaW5nZGEgS2EsIHRoZS';
UPDATE "Question" SET "questionEn" = 'If you are traveling at a speed of 80 km/h, how long will it take you to drive 80 km?', "questionFr" = 'Si vous roulez à une vitesse de 80 km/h, combien de temps vous faudra-t-il pour parcourir 80 km ?' WHERE "sourceId" = 'otd-SWYgeW91IGFyZSB0cmF2ZWxpbmcgYXQgYSBzcGVlZCBvZiA4MC';
UPDATE "Question" SET "questionEn" = 'What are the tallest twin buildings in the world, with a height of 452 m?', "questionFr" = 'Quels sont les plus hauts bâtiments jumeaux du monde, d''une hauteur de 452 m ?' WHERE "sourceId" = 'otd-V2hhdCBhcmUgdGhlIHRhbGxlc3QgdHdpbiBidWlsZGluZ3MgaW';
UPDATE "Question" SET "questionEn" = 'Out of these four buildings, which one is the tallest, with a height of 452 m?', "questionFr" = 'Parmi ces quatre bâtiments, lequel est le plus haut, avec une hauteur de 452 m ?' WHERE "sourceId" = 'otd-T3V0IG9mIHRoZXNlIGZvdXIgYnVpbGRpbmdzLCB3aGljaCBvbm';
UPDATE "Question" SET "questionEn" = 'On average, Americans consume 45 kg of what per second?', "questionFr" = 'En moyenne, les Américains consomment 45 kg de quoi par seconde ?' WHERE "sourceId" = 'otd-T24gYXZlcmFnZSwgQW1lcmljYW5zIGNvbnN1bWUgMTAwIHBvdW';
UPDATE "Question" SET "answersEn" = '["39 km/h", "322 km/h", "32 km/h", "24 km/h"]'::jsonb, "answersFr" = '["39 km/h", "322 km/h", "32 km/h", "24 km/h"]'::jsonb WHERE "sourceId" = 'otd-V2hhdCBpcyB0aGUgYWlyc3BlZWQgdmVsb2NpdHkgb2YgYW4gdW';
UPDATE "Question" SET "answersEn" = '["97 km/h", "64 km/h", "113 km/h", "80 km/h"]'::jsonb, "answersFr" = '["97 km/h", "64 km/h", "113 km/h", "80 km/h"]'::jsonb WHERE "sourceId" = 'otd-SW4gdGhlIDE5OTQgbW92aWUgJnF1b3Q7U3BlZWQmcXVvdDssIH';
UPDATE "Question" SET "answersEn" = '["373 m", "575 m", "597 m", "541 m"]'::jsonb, "answersFr" = '["373 m", "575 m", "597 m", "541 m"]'::jsonb WHERE "sourceId" = 'otd-SG93IHRhbGwgaXMgT25lIFdvcmxkIFRyYWRlIENlbnRlciBpbi';
UPDATE "Question" SET "questionEn" = 'What is the area of a circle with a diameter of 20 cm if π= 3.1415?', "answersEn" = '["380.1215 cm²", "3141.5 cm²", "1256.6 cm²", "314.15 cm²"]'::jsonb, "questionFr" = 'Quelle est l''aire d''un cercle dont le diamètre mesure 20 cm, si π = 3,1415 ?', "answersFr" = '["380,1215 cm²", "3 141,5 cm²", "1 256,6 cm²", "314,15 cm²"]'::jsonb WHERE "sourceId" = 'otd-V2hhdCBpcyB0aGUgYXJlYSBvZiBhIGNpcmNsZSB3aXRoIGEgZG';
UPDATE "Question" SET "questionEn" = 'In what year was the famous 14 m tall Hollywood sign first erected?', "questionFr" = 'En quelle année le célèbre panneau « Hollywood », haut de 14 mètres, a-t-il été érigé pour la première fois ?' WHERE "sourceId" = 'otd-SW4gd2hhdCB5ZWFyIHdhcyB0aGUgZmFtb3VzIDQ1IGZvb3QgdG';
UPDATE "Question" SET "answersEn" = '["268.8 m", "251.5 m", "317.6 m", "231.3 m"]'::jsonb, "answersFr" = '["268,8 m", "251,5 m", "317,6 m", "231,3 m"]'::jsonb WHERE "sourceId" = 'otd-V2hhdCB3YXMgdGhlIHRvdGFsIGxlbmd0aCBvZiB0aGUgVGl0YW';
UPDATE "Question" SET "answersEn" = '["9.461 Trillion Kilometres", "105.40 Earth-years", "1 AU", "806.6 Million Kilometres"]'::jsonb, "answersFr" = '["9 461 billions de kilomètres", "105,40 années terrestres", "1 AU", "806,6 millions de kilomètres"]'::jsonb WHERE "sourceId" = 'otd-SG93IGxvbmcgaXMgYSBsaWdodC15ZWFyPw==';
UPDATE "Question" SET "questionEn" = 'Death Valley''s Badwater Basin is North America''s point of lowest elevation at how many meters below sea level?', "answersEn" = '["24 meters", "3,686 meters", "86 meters", "500 meters"]'::jsonb, "questionFr" = 'Le bassin de Badwater, dans la Vallée de la Mort, est le point le plus bas d''Amérique du Nord. À combien de mètres sous le niveau de la mer se trouve-t-il ?', "answersFr" = '["24 mètres", "3 686 mètres", "86 mètres", "500 mètres"]'::jsonb WHERE "sourceId" = 'otd-RGVhdGggVmFsbGV5JiMwMzk7cyBCYWR3YXRlciBCYXNpbiBpcy';
UPDATE "Question" SET "questionEn" = 'The average woman is 13 centimeters shorter than the average man.', "questionFr" = 'Une femme mesure en moyenne 13 centimètres de moins qu''un homme.' WHERE "sourceId" = 'otd-VGhlIGF2ZXJhZ2Ugd29tYW4gaXMgNSBpbmNoZXMgLyAxMyBjZW';
UPDATE "Question" SET "questionEn" = 'What is the weight value of a Gold Bar in Fallout: New Vegas?', "answersEn" = '["30", "40", "32.5", "35"]'::jsonb, "questionFr" = 'Quelle est la valeur de poids d''un lingot d''or dans Fallout : New Vegas ?', "answersFr" = '["30", "40", "32,5", "35"]'::jsonb WHERE "sourceId" = 'otd-V2hhdCBpcyB0aGUgd2VpZ2h0IG9mIGEgR29sZCBCYXIgaW4gRm';
UPDATE "Question" SET "questionEn" = 'The video game "Fuel" has an open world that is 14,400 km²?', "questionFr" = 'Le jeu vidéo « Fuel » propose-t-il un monde ouvert de 14 400 km² ?' WHERE "sourceId" = 'otd-VGhlIHZpZGVvIGdhbWUgJnF1b3Q7RnVlbCZxdW90OyBoYXMgYW';
UPDATE "Question" SET "answersEn" = '["14 kg", "23 kg", "27 kg", "32 kg"]'::jsonb, "answersFr" = '["14 kg", "23 kg", "27 kg", "32 kg"]'::jsonb WHERE "sourceId" = 'otd-SG93IG11Y2ggd2VpZ2h0IGRpZCBDaHJpcyBQcmF0dCBsb3NlIG';
UPDATE "Question" SET "answersEn" = '["1.63 m", "1.70 m", "1.65 m", "1.75 m"]'::jsonb, "answersFr" = '["1,63 m", "1,70 m", "1,65 m", "1,75 m"]'::jsonb WHERE "sourceId" = 'otd-SG93IHRhbGwgaXMgVG9tIENydWlzZT8=';
UPDATE "Question" SET "answersEn" = '["5 meters", "23 meters", "15 meters", "7.5 meters"]'::jsonb, "answersFr" = '["5 mètres", "23 mètres", "15 mètres", "7,5 mètres"]'::jsonb WHERE "sourceId" = 'otd-QXQgd2hhdCBkZXB0aCBzaG91bGQgeW91IG1ha2UgYSBkZWNvbX';
UPDATE "Question" SET "answersEn" = '["14 kg", "4.5 kg", "9 kg", "7 kg"]'::jsonb, "answersFr" = '["14 kg", "4,5 kg", "9 kg", "7 kg"]'::jsonb WHERE "sourceId" = 'otd-SW4gJnF1b3Q7R3Jhdml0eSBGYWxscyZxdW90OywgaG93IG11Y2';
UPDATE "Question" SET "questionEn" = 'What UK Train does NOT go over 200 km/h?', "questionFr" = 'Quel train britannique ne dépasse PAS les 200 km/h ?' WHERE "sourceId" = 'otd-V2hhdCBVSyBUcmFpbiBkb2VzIE5PVCBnbyBvdmVyIDEyNU1QSD';
