-- Le tri de Musique et d'Histoire a déclassé presque toutes les questions OpenTriviaDB difficiles :
-- on complète le niveau difficile (50 questions minimum pour une partie solo) avec des questions
-- générées pointues mais correctes.
INSERT INTO "Question" ("id", "sourceId", "questionEn", "questionFr", "answersEn", "answersFr", "correctIndex", "category", "difficulty", "createdAt") VALUES
    (gen_random_uuid()::text, 'gen-d69e1bb9fe6f3269', 'In which city did Johnny Hallyday perform his first official stage show?', 'Dans quelle ville Johnny Hallyday a-t-il effectué sa première apparition officielle sur scène ?', '["Geneva", "Copenhagen", "Paris", "London"]'::jsonb, '["Genève", "Copenhague", "Paris", "Londres"]'::jsonb, 1, 'Music', 'hard', CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'gen-26eba736c855f081', 'What was the stage name used by young Edith Piaf when she performed with her father?', 'Quel était le nom de scène de la jeune Édith Piaf lorsqu''elle se produisait avec son père ?', '["Édith la voix d''or", "Miss Édith, phénomène vocal", "La petite chanteuse", "La môme Piaf"]'::jsonb, '["Édith la voix d''or", "Miss Édith, phénomène vocal", "La petite chanteuse", "La môme Piaf"]'::jsonb, 1, 'Music', 'hard', CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'gen-f0b2a675000e9358', 'Which producer and artistic director discovered and supported Jacques Brel during his difficult early years in Paris?', 'Quel producteur a soutenu et encouragé Jacques Brel à ses débuts à Paris ?', '["Charles Aznavour", "Jacques Canetti", "Bruno Coquatrix", "Eddie Barclay"]'::jsonb, '["Charles Aznavour", "Jacques Canetti", "Bruno Coquatrix", "Eddie Barclay"]'::jsonb, 1, 'Music', 'hard', CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'gen-57db11db8a219c58', 'In 1955, in which French town did Jacques Brel settle with his family?', 'En 1955, dans quelle ville française Jacques Brel s''installe-t-il avec sa famille ?', '["Lyon", "Lille", "Montreuil", "Paris"]'::jsonb, '["Lyon", "Lille", "Montreuil", "Paris"]'::jsonb, 2, 'Music', 'hard', CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'gen-cf585105f68a88e1', 'What is the name of the production label created by Stromae?', 'Quel est le nom du label de production créé par Stromae ?', '["Multitude", "Stromae Music", "Mosaert", "Racine"]'::jsonb, '["Multitude", "Stromae Music", "Mosaert", "Racine"]'::jsonb, 2, 'Music', 'hard', CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'gen-cb62567161cd4c00', 'Before her international career took off in the late 80s, Celine Dion took a break to improve her image and learn English. What was her last single released in France in 1986?', 'Avant de lancer sa carrière internationale, Céline Dion a fait une pause pour travailler son image. Quel était son single inédit sorti en France en 1986 ?', '["Une colombe", "Billy", "Mélanie", "Incognito"]'::jsonb, '["Une colombe", "Billy", "Mélanie", "Incognito"]'::jsonb, 1, 'Music', 'hard', CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'gen-6c51baac4622d9f5', 'Jean-Jacques Goldman''s brother, Robert, is also an author-composer known under the pseudonym J.Kapler.', 'Le frère de Jean-Jacques Goldman, Robert, est également auteur-compositeur sous le pseudonyme J.Kapler.', '["True", "False"]'::jsonb, '["Vrai", "Faux"]'::jsonb, 0, 'Music', 'hard', CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'gen-136460b692d5a0f4', 'Because of his dark complexion as a child, what nickname was Beethoven given?', 'À cause de son teint basané durant son enfance, quel surnom Beethoven a-t-il reçu ?', '["The German", "The Frenchman", "The Spaniard", "The Italian"]'::jsonb, '["L''Allemand", "Le Français", "L''Espagnol", "L''Italien"]'::jsonb, 2, 'Music', 'hard', CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'gen-81fa62517ebd56cf', 'Which composer and teacher first taught Beethoven piano, organ, and composition?', 'Quel compositeur et professeur a enseigné le piano, l''orgue et la composition à Beethoven ?', '["Christian Gottlob Neefe", "Johann Sebastian Bach", "Wolfgang Amadeus Mozart", "Joseph Haydn"]'::jsonb, '["Christian Gottlob Neefe", "Johann Sebastian Bach", "Wolfgang Amadeus Mozart", "Joseph Haydn"]'::jsonb, 0, 'Music', 'hard', CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'gen-b7eb8ce61cbe8157', 'Which American musician originally proposed the idea for the Fête de la musique in 1976?', 'Quel musicien américain a imaginé le concept de la Fête de la musique en 1976 ?', '["Joel Cohen", "André Henry", "Jacques Higelin", "Maurice Fleuret"]'::jsonb, '["Joel Cohen", "André Henry", "Jacques Higelin", "Maurice Fleuret"]'::jsonb, 0, 'Music', 'hard', CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'gen-ecab05c173b6788f', 'Before becoming famous as Akhenaton, what was the stage name of the IAM rapper?', 'Avant d''être connu sous le nom d''Akhenaton, quel était le nom de scène du rappeur d''IAM ?', '["Chill Phil", "Grand Organisateur DEF", "DJ Rebel", "Dope Rhyme Sayer"]'::jsonb, '["Chill Phil", "Grand Organisateur DEF", "DJ Rebel", "Dope Rhyme Sayer"]'::jsonb, 0, 'Music', 'hard', CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'gen-5cfb9bd66ccfc053', 'Paul McCartney joined the Quarrymen after auditioning with an Eddie Cochran song.', 'Paul McCartney a rejoint les Quarrymen après avoir auditionné avec une chanson d''Eddie Cochran.', '["True", "False"]'::jsonb, '["Vrai", "Faux"]'::jsonb, 0, 'Music', 'hard', CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'gen-a8a1ff0013bd690c', 'Where did the Beatles stay during their first Hamburg residency?', 'Où les Beatles étaient-ils logés lors de leur premier séjour à Hambourg ?', '["A cinema", "A music club", "A hotel", "A basement"]'::jsonb, '["Un cinéma", "Un club de musique", "Un hôtel", "Un sous-sol"]'::jsonb, 0, 'Music', 'hard', CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'gen-e99c9ff5e269f5ee', 'What was the name of the rhythm and blues group that Michael Jackson''s father played in?', 'Quel était le nom du groupe de rhythm and blues dans lequel jouait le père de Michael Jackson ?', '["The Ravens", "The Hawks", "The Eagles", "The Falcons"]'::jsonb, '["The Ravens", "The Hawks", "The Eagles", "The Falcons"]'::jsonb, 3, 'Music', 'hard', CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'gen-b7953693813e862c', 'When Jermaine Jackson left the group to start a solo career, who replaced him?', 'Qui a remplacé Jermaine Jackson au sein du groupe après son départ pour une carrière solo ?', '["Jackie", "Randy", "Tito", "Marlon"]'::jsonb, '["Jackie", "Randy", "Tito", "Marlon"]'::jsonb, 1, 'Music', 'hard', CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'gen-6897baed29672ba9', 'To promote his image as a young prodigy, Michael Jackson''s age was publicly reduced by two years when the band started.', 'Pour accentuer son image de jeune prodige, l''âge de Michael Jackson a été diminué de deux ans au début de la carrière du groupe.', '["True", "False"]'::jsonb, '["Vrai", "Faux"]'::jsonb, 0, 'Music', 'hard', CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'gen-0905fc4547759962', 'Before forming Queen, Brian May and Roger Taylor played in a band called Smile with which singer and bassist?', 'Avant de former Queen, Brian May et Roger Taylor jouaient dans le groupe Smile avec quel bassiste et chanteur ?', '["Tim Staffell", "John Deacon", "Mike Grose", "Freddie Mercury"]'::jsonb, '["Tim Staffell", "John Deacon", "Mike Grose", "Freddie Mercury"]'::jsonb, 0, 'Music', 'hard', CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'gen-b264afe244779824', 'Which Queen member sang lead vocals on the track ''Modern Times Rock ''n'' Roll''?', 'Quel membre de Queen assure le chant principal sur le titre « Modern Times Rock ''n'' Roll » ?', '["Freddie Mercury", "Roger Taylor", "John Deacon", "Brian May"]'::jsonb, '["Freddie Mercury", "Roger Taylor", "John Deacon", "Brian May"]'::jsonb, 1, 'Music', 'hard', CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'gen-46228e3ac363b208', 'Which film did Johnny Hallyday see at age 14 that triggered his passion for rock ''n'' roll?', 'Quel film Johnny Hallyday a-t-il vu à 14 ans, déclenchant sa passion pour le rock ''n'' roll ?', '["Loving You", "Blue Hawaii", "King Creole", "Jailhouse Rock"]'::jsonb, '["Amour frénétique", "Sous le ciel bleu d''Hawaï", "Bagarres au King Créole", "Le Rock du bagne"]'::jsonb, 0, 'Music', 'hard', CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'gen-643a9ceae9f00cee', 'What did the naturalist Daines Barrington suspect about young Mozart in London?', 'Que suspectait le naturaliste Daines Barrington à propos du jeune Mozart à Londres ?', '["That he was a trained monkey", "That he was a fraud", "That he was not actually blindfolded", "That he had a hidden teacher"]'::jsonb, '["Qu''il était un singe savant", "Qu''il était un imposteur", "Qu''il n''était pas réellement aveuglé", "Qu''il avait un professeur caché"]'::jsonb, 0, 'Music', 'hard', CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'gen-c1eeb97b68191a99', 'Which honorary title did Pope Clement XIV bestow upon the young Mozart during his time in Italy?', 'Quel titre honorifique le pape Clément XIV a-t-il décerné au jeune Mozart lors de son séjour en Italie ?', '["Maestro of Rome", "Prince of Music", "Knight of the Order of the Golden Spur", "Count of Salzburg"]'::jsonb, '["Maestro de Rome", "Prince de la musique", "Chevalier dans l''ordre de l''Éperon d''or", "Comte de Salzbourg"]'::jsonb, 2, 'Music', 'hard', CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'gen-063b58774df68457', 'When the Estates General were convened in 1788, which historical year''s format did the Parliament of Paris want to follow?', 'Lors de la convocation des états généraux en 1788, sur quel modèle historique le Parlement de Paris voulait-il s''appuyer ?', '["1515", "1614", "1715", "1492"]'::jsonb, '["1515", "1614", "1715", "1492"]'::jsonb, 1, 'History', 'hard', CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'gen-e69c5a32aa2e4c04', 'Which musical instrument did Louis XIV learn to play with Francesco Corbetta?', 'De quel instrument de musique Louis XIV a-t-il appris à jouer avec Francesco Corbetta ?', '["Guitar", "Lute", "Violin", "Harpsichord"]'::jsonb, '["La guitare", "Le luth", "Le violon", "Le clavecin"]'::jsonb, 0, 'History', 'hard', CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'gen-971a9114a3b89fd6', 'The Treaty of Verdun, which divided the empire, was signed by Charlemagne himself.', 'Le traité de Verdun, qui partagea l''Empire, a été signé par Charlemagne lui-même.', '["True", "False"]'::jsonb, '["Vrai", "Faux"]'::jsonb, 1, 'History', 'hard', CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'gen-e04824f6171767f1', 'Who is the author of the famous biography ''Vita Caroli''?', 'Qui est l''auteur de la célèbre biographie ''Vita Caroli'' ?', '["Thegan", "Ermold the Black", "Einhard", "Notker the Stammerer"]'::jsonb, '["Thegan", "Ermold le Noir", "Éginhard", "Notker le Bègue"]'::jsonb, 2, 'History', 'hard', CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'gen-08ea51a2a00fa702', 'Russia left the First World War in 1914.', 'La Russie a quitté la Première Guerre mondiale en 1914.', '["True", "False"]'::jsonb, '["Vrai", "Faux"]'::jsonb, 1, 'History', 'hard', CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'gen-4c11f789a5f4a33e', 'In which city did World War II officially end for the Asia-Pacific theater on September 2, 1945?', 'Dans quelle ville la Seconde Guerre mondiale s''est-elle officiellement achevée pour le théâtre Asie-Pacifique le 2 septembre 1945 ?', '["Nagasaki", "Tokyo", "Hiroshima", "Shanghai"]'::jsonb, '["Nagasaki", "Tokyo", "Hiroshima", "Shanghai"]'::jsonb, 1, 'History', 'hard', CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'gen-b4a763230a048801', 'Which 1937 event is considered the starting point of the second Sino-Japanese War?', 'Quel événement de 1937 est considéré comme le point de départ de la seconde guerre sino-japonaise ?', '["The invasion of Manchuria", "The attack on Pearl Harbor", "The Marco Polo Bridge incident", "The treaty of London"]'::jsonb, '["L''invasion de la Mandchourie", "L''attaque de Pearl Harbor", "L''incident du pont Marco-Polo", "Le traité de Londres"]'::jsonb, 2, 'History', 'hard', CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'gen-26b80fa387d95d9f', 'The rehearsal for the landing, known as Operation Tiger, was a complete success without any casualties.', 'La répétition du débarquement, appelée Opération Tigre, fut un succès total sans aucune perte humaine.', '["True", "False"]'::jsonb, '["Vrai", "Faux"]'::jsonb, 1, 'History', 'hard', CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'gen-d6f29f4e8076447e', 'What was the main purpose of the airborne operations on the eastern flank near the Orne river?', 'Quel était le but principal des opérations aéroportées sur le flanc est près de l''Orne ?', '["Prevent German tanks from reaching the beaches", "Destroy the German submarine fleet", "Establish a permanent base in Paris", "Capture the city of Caen"]'::jsonb, '["Empêcher les blindés allemands de rejoindre les plages", "Détruire la flotte sous-marine allemande", "Établir une base permanente à Paris", "Capturer la ville de Caen"]'::jsonb, 0, 'History', 'hard', CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'gen-f65fc6ceef27267e', 'What was the official code name for the operation to build the Berlin Wall?', 'Quel était le nom de code de l''opération de construction du mur de Berlin ?', '["Berlin Shield", "Iron Curtain", "Great Wall of China", "Operation Freedom"]'::jsonb, '["Bouclier de Berlin", "Rideau de fer", "Muraille de Chine", "Opération Liberté"]'::jsonb, 2, 'History', 'hard', CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'gen-00639e0a59dade2b', 'Some researchers believe that the legendary King Menes might actually be King Narmer.', 'Certains chercheurs pensent que le mythique roi Ménès pourrait en réalité être le roi Narmer.', '["True", "False"]'::jsonb, '["Vrai", "Faux"]'::jsonb, 0, 'History', 'hard', CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'gen-5e195095f0369f99', 'On the Narmer Palette, what color crown is the king wearing to symbolize his victory over Lower Egypt?', 'Sur la palette de Narmer, quelle couronne le roi porte-t-il pour symboliser sa victoire sur la Basse-Égypte ?', '["Gold", "Red", "White", "Blue"]'::jsonb, '["Dorée", "Rouge", "Blanche", "Bleue"]'::jsonb, 1, 'History', 'hard', CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'gen-985188889d19c37d', 'Recent research suggests the word ''Viking'' might actually originate from a term meaning what?', 'D''après des recherches récentes, le mot « Viking » viendrait d''un terme signifiant quoi ?', '["Bay dweller", "Changing rowers", "Northern king", "Gold seeker"]'::jsonb, '["Habitant de la baie", "Changement de rameur", "Roi du Nord", "Chercheur d''or"]'::jsonb, 1, 'History', 'hard', CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'gen-2cbba32a28fb953c', 'What two main factors brought an end to the Viking Age?', 'Quels sont les deux facteurs principaux ayant mis fin à l''âge viking ?', '["Centralized monarchies and conversion to Christianity", "The invention of the printing press", "The fall of the Roman Empire", "Global cooling and famine"]'::jsonb, '["Monarchies centralisées et conversion au christianisme", "L''invention de l''imprimerie", "La chute de l''Empire romain", "Refroidissement climatique et famine"]'::jsonb, 0, 'History', 'hard', CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'gen-d0388b68ed4a7116', 'From which Latin term, meaning ''marked by the cross'', does the word ''crusader'' originate?', 'De quel terme latin, signifiant « marqué par la croix », dérive le mot « croisé » ?', '["Expeditio", "Crucesignatus", "Iter hierosolymitanum", "Peregrinatio"]'::jsonb, '["Expeditio", "Crucesignatus", "Iter hierosolymitanum", "Peregrinatio"]'::jsonb, 1, 'History', 'hard', CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'gen-ac93f3c65431cf5d', 'Which people took control of Jerusalem in 1071, making pilgrimages more difficult?', 'Quel peuple prend le contrôle de Jérusalem en 1071, rendant les pèlerinages plus difficiles ?', '["Normans", "Byzantines", "Fatimids", "Seljuk Turks"]'::jsonb, '["Normands", "Byzantins", "Fatimides", "Turcs Seldjoukides"]'::jsonb, 3, 'History', 'hard', CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'gen-a02c44535f4e9e53', 'In the 8th century, which French city served as the capital for the Umayyad presence in Septimania?', 'Au VIIIe siècle, quelle ville française a servi de capitale à la présence omeyyade en Septimanie ?', '["Marseille", "Narbonne", "Bordeaux", "Toulouse"]'::jsonb, '["Marseille", "Narbonne", "Bordeaux", "Toulouse"]'::jsonb, 1, 'History', 'hard', CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'gen-5263a2d71c8a8b41', 'Which island served as the main base for Columbus''s colonization efforts, where he later lost his governing titles?', 'Quelle île a servi de base principale à la colonisation de Colomb, où il a fini par perdre ses titres de gouverneur ?', '["Puerto Rico", "Hispaniola", "Jamaica", "Cuba"]'::jsonb, '["Porto Rico", "Hispaniola", "Jamaïque", "Cuba"]'::jsonb, 1, 'History', 'hard', CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'gen-f58c81960ee537d7', 'At the very beginning of its creation, which power was Israel initially closer to?', 'Lors de sa création, de quel bloc l''État d''Israël était-il initialement le plus proche ?', '["The United Kingdom", "France", "The Soviet Union", "The United States"]'::jsonb, '["Le Royaume-Uni", "La France", "L''Union soviétique", "Les États-Unis"]'::jsonb, 2, 'History', 'hard', CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'gen-89e995c4a1cc3d2d', 'What is the name of the son of Aeneas who is considered the ancestor of the Iulii family?', 'Quel est le nom du fils d''Énée qui est considéré comme l''ancêtre de la famille des Iulii ?', '["Romulus", "Ascanius", "Remus", "Tullus"]'::jsonb, '["Romulus", "Ascagne", "Rémus", "Tullus"]'::jsonb, 1, 'History', 'hard', CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'gen-785305cce19bba0d', 'Which modern-day country encompasses the region of the Punjab where Alexander campaigned?', 'Dans quel pays actuel se situe la région du Pendjab où Alexandre a mené sa dernière campagne ?', '["Iran", "Pakistan", "Turkey", "Greece"]'::jsonb, '["Iran", "Pakistan", "Turquie", "Grèce"]'::jsonb, 1, 'History', 'hard', CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'gen-7cea88c7b424d3b4', 'Which author wrote the ''Anabasis'', a famous work about the military exploits of Alexander?', 'Quel auteur a écrit l''« Anabase », un ouvrage célèbre sur les exploits militaires d''Alexandre ?', '["Diodorus", "Plutarch", "Polybius", "Arrian"]'::jsonb, '["Diodore", "Plutarque", "Polybe", "Arrien"]'::jsonb, 3, 'History', 'hard', CURRENT_TIMESTAMP)
ON CONFLICT DO NOTHING;

INSERT INTO "Tag" ("id", "slug", "createdAt") VALUES
    (gen_random_uuid()::text, 'histoire', CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'johnny-hallyday', CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'lieu', CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'moyen-age', CURRENT_TIMESTAMP),
    (gen_random_uuid()::text, 'musique', CURRENT_TIMESTAMP)
ON CONFLICT ("slug") DO NOTHING;

INSERT INTO "_QuestionToTag" ("A", "B")
SELECT q."id", t."id" FROM (VALUES
    ('gen-d69e1bb9fe6f3269', 'johnny-hallyday'),
    ('gen-d69e1bb9fe6f3269', 'musique'),
    ('gen-26eba736c855f081', 'musique'),
    ('gen-f0b2a675000e9358', 'musique'),
    ('gen-57db11db8a219c58', 'lieu'),
    ('gen-57db11db8a219c58', 'musique'),
    ('gen-cf585105f68a88e1', 'musique'),
    ('gen-cb62567161cd4c00', 'musique'),
    ('gen-6c51baac4622d9f5', 'musique'),
    ('gen-136460b692d5a0f4', 'musique'),
    ('gen-81fa62517ebd56cf', 'musique'),
    ('gen-b7eb8ce61cbe8157', 'musique'),
    ('gen-ecab05c173b6788f', 'musique'),
    ('gen-5cfb9bd66ccfc053', 'musique'),
    ('gen-a8a1ff0013bd690c', 'musique'),
    ('gen-e99c9ff5e269f5ee', 'musique'),
    ('gen-b7953693813e862c', 'musique'),
    ('gen-6897baed29672ba9', 'musique'),
    ('gen-0905fc4547759962', 'musique'),
    ('gen-b264afe244779824', 'musique'),
    ('gen-46228e3ac363b208', 'johnny-hallyday'),
    ('gen-46228e3ac363b208', 'musique'),
    ('gen-643a9ceae9f00cee', 'musique'),
    ('gen-c1eeb97b68191a99', 'musique'),
    ('gen-063b58774df68457', 'histoire'),
    ('gen-e69c5a32aa2e4c04', 'histoire'),
    ('gen-e69c5a32aa2e4c04', 'musique'),
    ('gen-971a9114a3b89fd6', 'histoire'),
    ('gen-971a9114a3b89fd6', 'moyen-age'),
    ('gen-e04824f6171767f1', 'histoire'),
    ('gen-e04824f6171767f1', 'moyen-age'),
    ('gen-08ea51a2a00fa702', 'histoire'),
    ('gen-4c11f789a5f4a33e', 'histoire'),
    ('gen-b4a763230a048801', 'histoire'),
    ('gen-26b80fa387d95d9f', 'histoire'),
    ('gen-d6f29f4e8076447e', 'histoire'),
    ('gen-f65fc6ceef27267e', 'histoire'),
    ('gen-00639e0a59dade2b', 'histoire'),
    ('gen-5e195095f0369f99', 'histoire'),
    ('gen-985188889d19c37d', 'histoire'),
    ('gen-2cbba32a28fb953c', 'histoire'),
    ('gen-2cbba32a28fb953c', 'moyen-age'),
    ('gen-d0388b68ed4a7116', 'moyen-age'),
    ('gen-ac93f3c65431cf5d', 'histoire'),
    ('gen-ac93f3c65431cf5d', 'moyen-age'),
    ('gen-a02c44535f4e9e53', 'histoire'),
    ('gen-a02c44535f4e9e53', 'lieu'),
    ('gen-a02c44535f4e9e53', 'moyen-age'),
    ('gen-5263a2d71c8a8b41', 'histoire'),
    ('gen-f58c81960ee537d7', 'histoire'),
    ('gen-89e995c4a1cc3d2d', 'histoire'),
    ('gen-785305cce19bba0d', 'histoire'),
    ('gen-785305cce19bba0d', 'lieu'),
    ('gen-7cea88c7b424d3b4', 'histoire')
) AS l("sourceId", "slug")
JOIN "Question" q ON q."sourceId" = l."sourceId"
JOIN "Tag" t ON t."slug" = l."slug"
ON CONFLICT DO NOTHING;
