export const ErrorCode = {
	// auth
	AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
	AUTH_REFRESH_TOKEN_INVALID: 'AUTH_REFRESH_TOKEN_INVALID',
	AUTH_REFRESH_TOKEN_REVOKED: 'AUTH_REFRESH_TOKEN_REVOKED',
	AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
	AUTH_RESET_CODE_INVALID: 'AUTH_RESET_CODE_INVALID',
	AUTH_WRONG_PASSWORD: 'AUTH_WRONG_PASSWORD',
	PASSWORD_UNCHANGED: 'PASSWORD_UNCHANGED',

	// users
	EMAIL_ALREADY_USED: 'EMAIL_ALREADY_USED',
	USER_NOT_FOUND: 'USER_NOT_FOUND',
	FORBIDDEN_NOT_OWNER: 'FORBIDDEN_NOT_OWNER',
	AVATAR_LOCKED: 'AVATAR_LOCKED',

	// quiz
	CATEGORY_LOCKED: 'CATEGORY_LOCKED',
	NO_QUESTIONS_AVAILABLE: 'NO_QUESTIONS_AVAILABLE',
	SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
	SESSION_NOT_OWNED: 'SESSION_NOT_OWNED',
	SESSION_ALREADY_FINISHED: 'SESSION_ALREADY_FINISHED',
	SESSION_EXPIRED: 'SESSION_EXPIRED',
	INVALID_ANSWER_QUESTION: 'INVALID_ANSWER_QUESTION',

	// friends
	CANNOT_FRIEND_SELF: 'CANNOT_FRIEND_SELF',
	FRIEND_REQUEST_EXISTS: 'FRIEND_REQUEST_EXISTS',
	ALREADY_FRIENDS: 'ALREADY_FRIENDS',
	FRIEND_REQUEST_NOT_FOUND: 'FRIEND_REQUEST_NOT_FOUND',
	NOT_FRIENDS: 'NOT_FRIENDS',
	TOO_MANY_PENDING_REQUESTS: 'TOO_MANY_PENDING_REQUESTS',
	FRIEND_LIMIT_REACHED: 'FRIEND_LIMIT_REACHED',

	// games
	ALREADY_IN_GAME: 'ALREADY_IN_GAME',
	INVITATION_NOT_FOUND: 'INVITATION_NOT_FOUND',
	GAME_NOT_FOUND: 'GAME_NOT_FOUND',
	NOT_A_PLAYER: 'NOT_A_PLAYER',
	NOT_HOST: 'NOT_HOST',
	NOT_ENOUGH_PLAYERS: 'NOT_ENOUGH_PLAYERS',
	GAME_ALREADY_STARTED: 'GAME_ALREADY_STARTED',
	ANSWER_REJECTED: 'ANSWER_REJECTED',

	// websocket
	INVALID_PAYLOAD: 'INVALID_PAYLOAD',
	INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

// `message` reste en FR pour les logs/Bruno/debug — le frontend traduit sur
// `code`, avec repli sur ce message si le code n'est pas (encore) reconnu.
export function errorBody(code: ErrorCode, message: string) {
	return { code, message };
}
